@proxy
proxy_server = 127.0.0.1
proxy_port = 7890

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/delete/4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mary Poppendieck",
        "number": "39-23-6423122"
}